;EJEMPLO DE MACRO
DESPLEGAR MACRO MSG
    LEA DX,MSG
    MOV AH, 09H;INT 21h / AH=9 PETICION PARA DESPLEGAR, SALIDA DE UNA CADENA EN DS:DX. LA CADENA DEBE TERMINAR CON '$'.
    INT 21H
ENDM

.MODEL SMALL;MODELO PEQUEÑO DE COMPILACION(64K COMO MAXIMO)
.STACK ;.STACK = DEFINIR LA PILA DE DATOS
.DATA ;.DATA = LE INDICA AL ENSAMBLADOR QUE DEBE - 
      ;RESERVAR UN ESPACIO DE MEMORIA PARA LAS VARIABLES -QUE NOSOTROS DEFINAMOS
;----------------Declaracion de Variables-----------
VAR1 DB 'BREVE EJEMPLO DE CODIGO SOBRE MACROS $'
VAR2 DB 'LENGUAJE ENSAMBLADOR TASM $'

.CODE
MAIN  PROC FAR
MOV AX, @DATA;SE OBTIENE LA DIRECCION DE INICIO DEL SEGMENTO DE DATOS
MOV DS, AX ; SE ASIGNA AL REGISTRO DATA SEGMENT LA DIRECCION DE INICIO DEL SEGMENTO DE DATOS

DESPLEGAR VAR1

MOV AH,02H; INT 21h / AH=2 ESCRIBIR CARACTERES EN LA SALIDA ESTÁNDAR. ENTRADA: DL = CARÁCTER A ESCRIBIR, DESPUÉS DE LA EJECUCIÓN AL = DL.
MOV DL,0AH ;SALTO DE LINEA
INT 21H

MOV AH,02H
MOV DL,0DH ;RETORNO DE CARRO
INT 21H

DESPLEGAR VAR2

MOV AH,4CH; SE ASIGNA EL CÓDIGO PARA FINALIZACIÓN DE PROGRAMA
INT 21H; SI INVOCA A LA INTERRUPCIÓN DEL DOS 21H PARA FINALIZAR
MAIN ENDP
END MAIN

