;LABORATORIO NO.03
;Ejercicio1: Escriba un programa, en Lenguaje Ensamblador, Teniendo dos números de un dígito 
;ingresados por el usuario, realice las siguientes operaciones, debe tomar en cuenta que si el resultado es mayor a un dígito deberá imprimir los 2 dígitos.
;• Multiplicación (números naturales)
;• División (números naturales): Deberá generar el cociente y residuo.
;Tome en cuenta que deberá imprimir las instrucciones al usuario para leer los caracteres y textos que indiquen el resultado.
;JULIO ANTHONY ENGELS RUIZ COTO 1284719

.MODEL SMALL
.STACK     ;.STACK = DEFINIR LA PILA DE DATOS
.DATA        ;.DATA = LE INDICA AL ENSAMBLADOR QUE DEBE - 
            ;RESERVAR UN ESPACIO DE MEMORIA PARA LAS VARIABLES - 
            ;QUE NOSOTROS DEFINAMOS
;----------------Declaracion de Variables-----------
MENU  db "              BIENVENIDO AL LABORATORIO 3 MICROPROGRAMACION URL ",13,10
      db "INGRESE LA OPCION A REALIZAR: ",13,10
      db "1. MULTIPLICACION",13,10
      db "2. DIVISION",13,10
      db "3. EXIT",13,10,'$'

LABELERROR db "OPCION INCORRECTA. VUELVA A INTENTARLO NUEVAMENTE. "
ENTRAR DB 0DH, 0AH,"$" ;ODH=CR=retorno de carro-enter
                       ;OAH=LF=salto de linea
VAR1 DB ?
VAR2 DB ?
VARRESTA DB ?
VARDIVI DB ?
UNIDAD DB ?
DECENA DB ?
RESTO DB ?
COCIENTE DB ?
SIGN DB "-","$"

MSJO3 DB "SELECCIONASTE LA OPCION 1 (MULTIPLICACION):","$"
MSJO4 DB "SELECCIONASTE LA OPCION 2 (DIVISION):","$"
;-------------------------------------------------
RES3 DB "LA RESPUESTA DE LA OPERACION MULTIPLICACION ES: ","$"
RES4 DB "LA RESPUESTA DE LA OPERACION DIVISION ES - COCIENTE: ","$"
RES41 DB "LA RESPUESTA DE LA OPERACION DIVISION ES - RESIDUO: ","$"
;---------------------------------------------------
MSGE1 DB "INGRESE SU PRIMER VALOR: ","$"
MSGE2 DB "INGRESE SU SEGUNDO VALOR: ","$"
;---------------------------------------------------
ADIOS DB "ADIOS GRACIAS POR USAR MI PROGRAMA ;)" ,"$"
ERROR DB "CARACTER INVALIDO","$"
VERIFICACION DB "DESEA CONTINUAR CON EL PROGRAMA? : PRESIONE (1) - CONTINUAR | (2) - SALIR " , "$"
.CODE
MAIN  PROC FAR
MOV AX, @data;SE OBTIENE LA DIRECCION DE INICIO DEL SEGMENTO DE DATOS
MOV DS, AX ; SE ASIGNA AL REGISTRO DATA SEGMENT LA DIRECCION DE INICIO DEL SEGMENTO DE DATOS

;CALL BORRAR_TEXPAN
;------------------INICIO-----------------------------
CALL INICIO

;--------------------FIN-----------------------------
SALIDA:
  CALL FUNCION_SALTOLINEA
  MOV DX,OFFSET ADIOS
  MOV AH, 09H
  INT 21H

  MOV AH, 4CH
  INT 21H
;----------------------------------------------------
INICIO PROC
  CALL BORRAR_TEXPAN     
  CALL ENSE_MENU 
  CALL SELECCION_EJERCICIO
  RET
INICIO ENDP

 ;PROCEDIMIENTO PARA FUNCION_SALTOLINEA UN RENGLON EN LA PANTALLA
FUNCION_SALTOLINEA PROC NEAR
	MOV DX,OFFSET ENTRAR 
	MOV AH, 09H
	INT 21H
	RET
FUNCION_SALTOLINEA	ENDP

;PROCEDIMIENTO DE LECTURA DE VALORES DE 1 DIGITO
VAL_UNDIGITO PROC 
	MOV DX,OFFSET MSGE1 
	MOV AH,09H;SALIDA DE UNA CADENA EN DS:DX. LA CADENA DEBE TERMINAR CON'$'.
	INT 21h
	MOV AH,01H;LEE EL CARÁCTER DE LA ENTRADA ESTÁNDAR, CON ECO, EL RESULTADO SE ALMACENA EN AL.SI NO HAY NINGÚN CARÁCTER EN EL BÚFER DEL TECLADO, LA FUNCIÓN ESPERA HASTA QUE SE PRESIONE CUALQUIER TECLA.
	INT 21h
	SUB AL,30H
	MOV VAR1,AL

	CALL FUNCION_SALTOLINEA

	MOV DX,OFFSET MSGE2
	MOV AH,09H
	INT 21h
	MOV AH,01h
	INT 21h
	SUB AL,30H
	MOV VAR2,AL

	CALL FUNCION_SALTOLINEA
	RET
VAL_UNDIGITO ENDP

SELECCION_EJERCICIO PROC
;------ESPERA ALGUNA TECLA--------------------------- 
;01/30H LEE EL CARÁCTER DE LA ENTRADA ESTÁNDAR, CON ECO, EL RESULTADO SE ALMACENA EN AL.SI NO HAY NINGÚN CARÁCTER EN EL BÚFER DEL TECLADO, LA FUNCIÓN ESPERA HASTA QUE SE PRESIONE CUALQUIER TECLA. 
  MOV AH,01H
  INT 21H
  SUB AL,30H
  CMP AL,1
  JE EJERCICIO_UNO
  CMP AL,2
  JE EJERCICIO_DOS
  CMP AL,3
  JE SALIDA
  JMP ETIQUETA_ERROR

ETIQUETA_ERROR:
  MOV DX,OFFSET LABELERROR 
  MOV AH,09h
  INT 21H
  JMP INICIO
  RET
SELECCION_EJERCICIO ENDP

EJERCICIO_UNO PROC
  CALL FUNCION_SALTOLINEA
  MOV DX,OFFSET MSJO3
  MOV AH,09H    
  INT 21H
  CALL FUNCION_SALTOLINEA
  CALL VAL_UNDIGITO
  XOR AX,AX ; HACEMOS UNA LIMPIEZA DEL REGISTRO AX
  ;-----------------A * B ------------------------------
  MOV AL,VAR1
  MOV BL,VAR2
  MUL BL;EN AL SE GUARDA VAR1 Y MUL=AL*BL SI INGRESO 4 Y 4 AX GUARDARA 16
  ;AQUI EN AAM AH = 01, Y AL = 06
  AAM ;AJUSTE ASCII PARA MULTIPLICACION - CORRIGE EL RESULTADO DE LA MULTIPLICACIÓN DE DOS VALORES BCD.
  MOV DECENA,AH 
  MOV UNIDAD,AL  
  ;DECENA, UNIDAD <===

  MOV DX,OFFSET RES3
  MOV AH,09H 
  INT 21H
  ;02/21H ESCRIBIR CARACTERES EN LA SALIDA ESTÁNDAR ENTRADA: DL = CARÁCTER A ESCRIBIR, DESPUÉS DE LA EJECUCIÓN AL = DL.
  MOV AH,02H 
  MOV DL,DECENA 
  ADD DL,30H ;AJUSTAS EL VALOR ENTERO PARA SER DESPLEGADO EN LA PANTALLA COMO VALOR CARACTER.
  INT 21H 

  MOV AH,02H
  MOV DL,UNIDAD   
  ADD DL,30H 
  INT 21H 

  CALL FUNCION_SALTOLINEA
  CALL VERIFICACION_DE_SEGUIMIENTO
  RET
EJERCICIO_UNO ENDP

EJERCICIO_DOS PROC
  CALL FUNCION_SALTOLINEA
  MOV DX,OFFSET MSJO4
  MOV AH,09H    
  INT 21H
  CALL FUNCION_SALTOLINEA
  CALL VAL_UNDIGITO
  XOR AX,AX ; HACEMOS UNA LIMPIEZA DEL REGISTRO AX
  ;-----------------A % B ------------------------------
  MOV AL,VAR1  ;203/4
  DIV VAR2  ;AL = 50->COCIENTE Y AH = 3->RESIDUO
  MOV COCIENTE,AL
  MOV RESTO,AH

  MOV DX,OFFSET RES4
  MOV AH,09H 
  INT 21H 
  ;-------COCIENTE-----
  MOV AH,02H
  MOV DL,COCIENTE  
  ADD DL,30H 
  INT 21H 
  CALL FUNCION_SALTOLINEA
  MOV DX,OFFSET RES41
  MOV AH,09H 
  INT 21H 
  ;--------RESTO-------
  MOV AH,02H
  MOV DL,RESTO  
  ADD DL,30H 
  INT 21H

  CALL FUNCION_SALTOLINEA
  CALL VERIFICACION_DE_SEGUIMIENTO
  RET
EJERCICIO_DOS ENDP

ETIQUETA_DE_SALTO_HACIA_INICIO: 
  JMP INICIO
ETIQUETA_DE_SALTO_HACIA_SALIDA: 
  JMP SALIDA
ETIQUETA_DE_SALTO_HACIA_INICIO1:
  JMP ETIQUETA_DE_SALTO_HACIA_INICIO
ETIQUETA_DE_SALTO_HACIA_SALIDA1:
  JMP ETIQUETA_DE_SALTO_HACIA_SALIDA

ENSE_MENU PROC
  MOV DX, OFFSET MENU
  MOV AH, 09H; PETICION PARA DESPLEGAR
  INT 21H; LLAMA AL DOS
  RET
ENSE_MENU ENDP

BORRAR_TEXPAN PROC
;INT 10H / AH = 0 - COLOCA EL MODO DE VIDEO.
;INPUT:
;AL = MODO DE VIDEO DESEADO.
;ESTOS MODOS DE VIDEO SON COMPATIBLES:
;00H - MODO TEXTO. 40X25. 16 COLORES. 8 PÁGINAS.
  MOV AH, 00H
  MOV AL, 3
  INT 10H
  RET
BORRAR_TEXPAN ENDP

VERIFICACION_DE_SEGUIMIENTO PROC
  MOV DX, OFFSET VERIFICACION
  MOV AH,09H 
  INT 21H 
  CALL FUNCION_SALTOLINEA
  ;------ESPERA ALGUNA TECLA--------------------------- 
;01/30H LEE EL CARÁCTER DE LA ENTRADA ESTÁNDAR, CON ECO, EL RESULTADO SE ALMACENA EN AL.SI NO HAY NINGÚN CARÁCTER EN EL BÚFER DEL TECLADO, LA FUNCIÓN ESPERA HASTA QUE SE PRESIONE CUALQUIER TECLA. 
  MOV AH,01H
  INT 21H
  SUB AL,30H
  CMP AL,1
  JE ETIQUETA_DE_SALTO_HACIA_INICIO1
  CMP AL,2
  JE ETIQUETA_DE_SALTO_HACIA_SALIDA1
  JMP ETIQUETA_ERROR

  RET
VERIFICACION_DE_SEGUIMIENTO ENDP

MAIN ENDP
END MAIN